export interface Product {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  tagline: string;
  description: string;
  features: string[];
  applications: string[];
  brand?: string;
  image?: string;
  specs?: { label: string; value: string }[];
}

const BASE = "https://demo.virtualxcellence.com/greenwatt/wp-content/uploads";

export const products: Product[] = [
  {
    slug: "thermal-imagers",
    name: "Thermal Imagers",
    category: "Thermal & Optical Imaging",
    categorySlug: "pd-ir-uv",
    tagline: "Infrared Cameras for Electrical Diagnostics",
    brand: "Satir",
    image: `${BASE}/2026/04/thermal-imaging-gas-infrared-camera-500x500-1.png`,
    description:
      "Thermal imaging is the most efficient method of identifying hot spots, overloaded connections, failing components, and insulation weaknesses in energised electrical systems — all without contact and without interrupting supply. Green Watt supplies a range of infrared cameras covering entry-level handheld models through to high-resolution professional systems used in substation and industrial audits.",
    features: [
      "Temperature range −20°C to +2000°C (model dependent)",
      "Thermal sensitivity (NETD) ≤ 50 mK",
      "Real-time visible-light and thermal image fusion",
      "IP54-rated rugged housing for field use",
      "Min/max/average spot temperature markers",
      "Isotherm and alarm threshold setting",
      "USB connectivity and report generation software",
      "Models: CK350, EP3501, G96, YRH600, Mini-R series",
    ],
    applications: [
      "Substation primary equipment inspection (transformers, busbars, cable terminations)",
      "LT panel, MCC, and switchboard surveys",
      "Overhead transmission and distribution line patrol",
      "Motor bearing and mechanical hot-spot detection",
      "Solar PV panel thermal survey for cell defects",
    ],
    specs: [
      { label: "Detector Resolution", value: "320×240 to 640×480 (model dependent)" },
      { label: "Thermal Sensitivity", value: "≤ 50 mK" },
      { label: "Temperature Range", value: "−20°C to +2000°C" },
      { label: "Image Storage", value: "Internal memory + SD card" },
      { label: "Protection Rating", value: "IP54 (selected models)" },
    ],
  },
  {
    slug: "relay-testing-equipment",
    name: "Relay Testing Equipment",
    category: "Protection & Relay Testing",
    categorySlug: "relay-testing",
    tagline: "Kingsine K3063i & K68i Protection Relay Test Systems",
    brand: "Kingsine",
    image: `${BASE}/2026/04/K3063i_L_15D-GW-Kingsine-min-300x200-2.png`,
    description:
      "Green Watt is an authorised partner for Kingsine, a globally recognised manufacturer of protection relay test sets. Kingsine instruments are used by power utilities, relay manufacturers, and commissioning engineers worldwide to verify the performance of electromechanical, static, and numerical protection relays.",
    features: [
      "3 voltage + 3 current outputs (K3063i), expandable to 6 current channels",
      "High current output up to 90 A per channel for electromechanical relays",
      "Integrated 10-inch touch screen on K68i — no laptop required",
      "IEC 61850-8-1 GOOSE and IEC 61850-9-2 sampled values support",
      "GPS/IRIG-B synchronisation for differential relay testing",
      "Pre-defined test templates for IEC, IEEE, and ANSI relay standards",
      "Automated test reporting with PDF export",
      "Rugged aluminium case for field transport",
    ],
    applications: [
      "Commissioning of new protection relay panels in 11 kV to 400 kV substations",
      "Periodic testing per Indian Grid Code requirements",
      "Factory acceptance testing of relay panels",
      "Fault investigation — verification of relay operation during system disturbances",
      "Differential, distance, overcurrent, and bus protection testing",
    ],
    specs: [
      { label: "Voltage Outputs", value: "3 × V (K3063i), 6 × V (K68i)" },
      { label: "Current Outputs", value: "3 × I expandable to 6 (K3063i), 6 × I (K68i)" },
      { label: "Max Current Output", value: "Up to 90 A per channel" },
      { label: "Communications", value: "IEC 61850 GOOSE, Sampled Values, GPS/IRIG-B" },
      { label: "Interface", value: "PC software (K3063i) / Integrated touchscreen (K68i)" },
    ],
  },
  {
    slug: "ct-pt-analyzer",
    name: "CT/PT Analyzer",
    category: "Transformer Diagnostics",
    categorySlug: "primary-test-equipment",
    tagline: "Current & Potential Transformer Test System",
    image: `${BASE}/2026/04/Gemini-1.png`,
    description:
      "The Green Watt CT/PT Analyzer is a fully automated, portable instrument for comprehensive testing of current transformers (CTs) and potential transformers (PTs/VTs). It verifies transformer parameters on site without the need for a laboratory — ensuring metering integrity and protection relay dependability.",
    features: [
      "Fully automated test sequence with one-button operation",
      "Ratio accuracy, phase displacement, and excitation curve measurement",
      "Knee-point voltage (Vk) and exciting current measurement for protection CTs",
      "Burden measurement at rated secondary current",
      "High-voltage excitation source built in — no external HV supply required",
      "Colour touch-screen with graphical excitation curve plotting",
      "Automatic data storage with time-stamped test reports",
      "USB and RS-232 output for PC-based report generation",
    ],
    applications: [
      "New CT/PT commissioning in 11 kV to 400 kV substations",
      "Periodic statutory testing of revenue metering CTs and PTs",
      "Post-fault investigation of protection CT saturation events",
      "Acceptance testing of CT/PT batches at manufacturer's works",
    ],
    specs: [
      { label: "Standards", value: "IEC 61869, IS 2705, IEEE C57.13" },
      { label: "CT Ratio Range", value: "Covers distribution to EHV" },
      { label: "Interface", value: "Colour touch-screen, USB, RS-232" },
      { label: "Power", value: "Battery-powered for field use" },
    ],
  },
  {
    slug: "solar-pv-testing",
    name: "Solar PV Testing Equipment",
    category: "Solar PV Testing",
    categorySlug: "solar-pv",
    tagline: "I-V Curve Tracing & PV System Commissioning Instruments",
    image: `${BASE}/2026/04/seaward-pv200-a-compact-solar-pv-tester-with-i-v-curve-tracing-500x500-1.png`,
    brand: "MULTI-JAPAN",
    description:
      "Green Watt supplies a comprehensive range of solar PV test instruments, enabling EPC contractors, O&M providers, and utilities to verify PV system performance, detect faults, and maintain compliance with IEC 62446 and other applicable standards. Instruments are sourced from MULTI-JAPAN for high-precision performance.",
    features: [
      "MCM1600PV: I-V and P-V curve tracing up to 1500 V / 30 A",
      "STC normalisation of measured I-V curve for datasheet comparison",
      "Bipolar insulation resistance measurement without disconnecting the array",
      "NSEI-100D: precision solar irradiance and data logging",
      "MDLA-100A-DC: up to 16 DC current channels for string monitoring",
      "Spectral irradiance correction using reference cell or pyranometer",
      "Bluetooth data transfer and dedicated smartphone app",
      "Compliant with IEC 62446-1",
    ],
    applications: [
      "PV system commissioning per IEC 62446-1 and IEC 62446-3",
      "String-level fault finding: shading, bypass diode failures, soiling",
      "O&M performance monitoring and yield optimisation",
      "Insurance and bankability assessment for solar assets",
    ],
    specs: [
      { label: "MCM1600PV Voltage Range", value: "Up to 1500 V DC" },
      { label: "MCM1600PV Current Range", value: "Up to 30 A" },
      { label: "Insulation Test Voltage", value: "250 V to 1500 V DC" },
      { label: "Standard Compliance", value: "IEC 62446-1, IEC 62446-3" },
      { label: "Data Transfer", value: "Bluetooth, USB" },
    ],
  },
  {
    slug: "gas-detection-cameras",
    name: "Gas Detection Cameras",
    category: "Thermal & Optical Imaging",
    categorySlug: "pd-ir-uv",
    tagline: "SF6 Gas Leak Detection & UV Corona Cameras",
    brand: "OFIL Systems / Satir",
    description:
      "Green Watt supplies advanced optical cameras for two critical but invisible electrical hazards: SF6 gas leaks in gas-insulated switchgear and circuit breakers, and corona discharge on overhead lines and high-voltage equipment. Cameras sourced from OFIL Systems (UV corona) and Satir (thermal/gas OGI) allow operators to locate leaks and discharge activity quickly and safely without taking equipment out of service.",
    features: [
      "Infrared OGI camera makes SF6 leaks visible as a dark smoke-like image",
      "OFIL DayCor® solar-blind UV cameras — fully operational in daylight",
      "No equipment shutdown required for SF6 leak surveys",
      "UV corona quantification via photon count display",
      "Simultaneous UV + visible-light fusion image display",
      "Zoom lenses for inspection of transmission towers from ground level",
      "GPS-tagged video and image data logging",
      "Also detects hydrocarbon gases, CO₂, and refrigerant gases (OGI models)",
    ],
    applications: [
      "GIS substation SF6 leak surveys",
      "Ring main unit (RMU) and SF6 CB leak detection",
      "Transmission line corona survey (insulators, conductors, fittings)",
      "Cable sealing end and surge arrester corona inspection",
      "Environmental compliance monitoring of SF6-insulated equipment",
    ],
    specs: [
      { label: "UV Detection Band", value: "240–280 nm (solar-blind)" },
      { label: "OGI Detector", value: "Cooled MCT IR detector" },
      { label: "Operation", value: "In service — no shutdown required" },
      { label: "Application", value: "GIS, RMU, overhead lines, cables" },
    ],
  },
  {
    slug: "hipot-vlf-testers",
    name: "Hipot & VLF Testers",
    category: "High-Voltage & Insulation Testing",
    categorySlug: "hv-insulation",
    tagline: "High-Voltage Cable and Equipment Test Systems",
    description:
      "High-voltage withstand testing verifies the dielectric integrity of cable insulation, transformer windings, switchgear, and other HV apparatus at commissioning and during periodic maintenance. Green Watt supplies AC hipot, DC hipot, and VLF (Very Low Frequency) test systems — offering the right high-voltage testing tool for every application.",
    features: [
      "AC Hipot: 5 kV to 100 kV AC output for power-frequency withstand testing",
      "DC Hipot: up to 80 kV DC with ultra-low ripple for leakage current measurement",
      "VLF: 0.1 Hz test at up to 72 kV for practical testing of long cable circuits",
      "Tan delta measurement at VLF frequency for cable condition assessment",
      "Leakage current profile display and step-voltage test mode",
      "Automatic pass/fail indication with trip threshold setting",
      "Built-in automatic discharge with residual voltage indicator",
      "Single-operator portable design for site use without mains power (VLF)",
    ],
    applications: [
      "Factory and site acceptance testing of HV cables and cable systems",
      "Post-repair hipot testing of cable joints and terminations",
      "Transformer and switchgear withstand testing",
      "Pre-commissioning testing of GIS",
      "Periodic dielectric testing of aged cable circuits",
    ],
    specs: [
      { label: "AC Hipot Output", value: "5 kV to 100 kV AC" },
      { label: "DC Hipot Output", value: "Up to 80 kV DC" },
      { label: "VLF Output", value: "Up to 72 kV at 0.1 Hz" },
      { label: "VLF Frequency", value: "0.1 Hz sinusoidal / cosine-rectangular" },
    ],
  },
  {
    slug: "insulation-testers",
    name: "Insulation Testers",
    category: "High-Voltage & Insulation Testing",
    categorySlug: "hv-insulation",
    tagline: "Insulation Resistance Test Instruments (Megohmmeters)",
    description:
      "Insulation resistance testing is one of the most fundamental preventive maintenance checks on electrical equipment. A drop in insulation resistance gives early warning of moisture ingress, contamination, ageing, and physical damage. Green Watt supplies a range of insulation testers covering standard electrical equipment, solar PV systems, and high-resistance applications.",
    features: [
      "Test voltages: 250 V, 500 V, 1000 V, 2500 V, 5000 V (model dependent)",
      "Measurement range: up to 10 TΩ",
      "PI (Polarisation Index) and DAR automatic calculation",
      "Step voltage and ramp voltage test modes",
      "Solar PV bipolar insulation measurement without disconnecting arrays",
      "Temperature-compensated readings (PV models)",
      "Auto-discharge circuit after testing — safe for operators",
      "Data logging with USB download and CAT IV safety rating",
    ],
    applications: [
      "Motor and generator winding insulation assessment",
      "Power cable and cable joint insulation testing",
      "Transformer winding insulation before energisation",
      "Solar PV system commissioning per IEC 62446",
      "Switchgear and busbar insulation checks",
    ],
    specs: [
      { label: "Test Voltages", value: "250 V to 5000 V DC" },
      { label: "Measurement Range", value: "Up to 10 TΩ" },
      { label: "PV Test Voltage", value: "Up to 1500 V DC (PV models)" },
      { label: "Safety Rating", value: "CAT IV" },
    ],
  },
  {
    slug: "partial-discharge-detectors",
    name: "Partial Discharge Detectors",
    category: "Partial Discharge & Cable Diagnostics",
    categorySlug: "pd-ir-uv",
    tagline: "Detect Insulation Defects Before They Cause Failures",
    description:
      "Partial discharge (PD) is one of the most reliable early indicators of insulation degradation in high-voltage cables, transformers, switchgear, and rotating machines. Green Watt supplies a range of PD detection instruments — from entry-level analogue detectors to sophisticated multi-channel digital systems — enabling maintenance teams to locate and quantify PD activity without taking equipment out of service.",
    features: [
      "Penta-PD: five simultaneous channels with UHF, TEV, acoustic, and HFCT inputs",
      "Phase-resolved partial discharge (PRPD) pattern display for defect classification",
      "GPS-tagged measurement logging for site mapping",
      "Digital model with IEC 60270-compliant calibration pulse injection",
      "Wireless sensor option for remote or hazardous locations",
      "Narrowband and wideband detection modes",
      "Rechargeable battery with minimum 8 hours field operation",
      "Compact handheld form factor with touch screen interface",
    ],
    applications: [
      "Condition assessment of XLPE and PILC power cables",
      "Transformer bushing and winding insulation surveys",
      "GIS compartment integrity checks",
      "Rotating machine stator insulation monitoring",
    ],
    specs: [
      { label: "Penta-PD Channels", value: "5 simultaneous measurement channels" },
      { label: "Sensor Types", value: "UHF, TEV, HFCT, Acoustic (AE)" },
      { label: "Display", value: "Phase-resolved PD (PRPD) patterns" },
      { label: "Battery Life", value: "Minimum 8 hours" },
      { label: "Standard", value: "IEC 60270 (calibration)" },
    ],
  },
  {
    slug: "sfra-testing",
    name: "SFRA Testing",
    category: "Transformer Diagnostics",
    categorySlug: "primary-test-equipment",
    tagline: "Sweep Frequency Response Analysis for Power Transformers",
    description:
      "SFRA (Sweep Frequency Response Analysis) is the most sensitive technique for detecting mechanical deformation of power transformer windings and core — damage that can occur during short-circuit events, transportation incidents, or seismic events. Green Watt's SFRA systems allow asset managers to assess whether a transformer's internal geometry has changed without opening the tank.",
    features: [
      "Wide frequency sweep: 20 Hz to 2 MHz for full winding, core, and bushing coverage",
      "High dynamic range: up to 100 dB for detecting subtle deformation signatures",
      "Complete sweep in under 1 minute per winding terminal pair",
      "Standard test connections per IEC 60076-18 / CIGRE TB342",
      "Automatic comparison against stored baseline with deviation reporting",
      "Fingerprint database for trend analysis across multiple measurement campaigns",
      "PC software with phase angle plots and automated assessment",
      "Lightweight portable unit in a single carry case",
    ],
    applications: [
      "Post-short-circuit assessment before returning a transformer to service",
      "Pre- and post-transportation fingerprinting for new and repaired transformers",
      "Routine asset condition assessment for transformer life management",
      "Post-seismic event verification",
      "Ranking transformers for prioritised refurbishment or replacement",
    ],
    specs: [
      { label: "Frequency Range", value: "20 Hz to 2 MHz" },
      { label: "Dynamic Range", value: "Up to 100 dB" },
      { label: "Test Time", value: "< 1 minute per terminal pair" },
      { label: "Standards", value: "IEC 60076-18, CIGRE TB342, IEEE C57.149" },
    ],
  },
  {
    slug: "tan-delta-tester",
    name: "Tan Delta Tester",
    category: "Transformer Diagnostics",
    categorySlug: "primary-test-equipment",
    tagline: "Insulation Power Factor & Dissipation Factor Test Set",
    description:
      "The tan delta test is one of the most sensitive diagnostic tests for assessing transformer main insulation, bushing insulation, cable insulation, and rotating machine windings. Unlike simple insulation resistance testing, the tan delta measurement detects distributed moisture, contamination, and ageing even before there is a measurable drop in insulation resistance.",
    features: [
      "High-voltage output: up to 12 kV, 28 kV, or higher (model dependent)",
      "Simultaneous capacitance and tan delta measurement",
      "Grounded (UST) and ungrounded (GST) test modes",
      "Guard terminal for eliminating stray surface leakage currents",
      "Voltage dependency (tip-up) test — automatic multi-voltage measurement",
      "Tan δ resolution of 0.1 × 10⁻⁴ or better",
      "Temperature logging for correction to reference temperature",
      "Automated report with pass/fail against IEEE C57.12.90 and IEC 60137 limits",
    ],
    applications: [
      "Power transformer main insulation and bushing tan delta at commissioning and maintenance",
      "Generator and motor stator winding insulation assessment",
      "High-voltage cable insulation condition monitoring",
      "CT and VT insulation testing",
      "Surge arrester and capacitor bank insulation checks",
    ],
    specs: [
      { label: "Output Voltage", value: "Up to 28 kV AC (model dependent)" },
      { label: "Tan δ Resolution", value: "0.1 × 10⁻⁴" },
      { label: "Test Modes", value: "UST (ungrounded), GST (grounded), Guard" },
      { label: "Standards", value: "IEEE C57.12.90, IEC 60137, IEC 60243" },
    ],
  },
  {
    slug: "oil-bdv-tester",
    name: "Oil BDV Tester",
    category: "Transformer Diagnostics",
    categorySlug: "primary-test-equipment",
    tagline: "Automatic Transformer Oil Breakdown Voltage Test Set",
    description:
      "The dielectric breakdown voltage (BDV) of transformer insulating oil is a primary indicator of oil quality and contamination. Green Watt's automatic oil BDV tester performs the breakdown test to IEC 60156 / IS 335 standards, giving maintenance engineers a reliable, repeatable assessment of oil condition in the field or workshop.",
    features: [
      "Fully automatic test cycle — electrode gap, oil stirring, voltage ramp, breakdown detection",
      "Test voltage up to 100 kV AC",
      "IEC 60156 compliant test ramp rate (2 kV/s)",
      "Six-shot automatic test sequence with mean BDV calculation",
      "Motorised oil stirrer to disperse carbon particles between shots",
      "Safety interlocks — HV door interlock and automatic discharge after each shot",
      "Automatic report with date, time, operator, and sample identification",
      "Standard IEC 60156 test cell with 2.5 mm spherical electrodes",
    ],
    applications: [
      "Routine condition monitoring of transformer insulating oil",
      "Acceptance testing of new transformer oil on delivery",
      "Post-degassing and oil filtration quality verification",
      "Fault investigation — oil quality check following a transformer incident",
      "Oil reclamation plant quality control",
    ],
    specs: [
      { label: "Test Voltage", value: "Up to 100 kV AC" },
      { label: "Ramp Rate", value: "2 kV/s (IEC 60156)" },
      { label: "Test Sequence", value: "6 automatic breakdown shots" },
      { label: "Electrode Gap", value: "2.5 mm spherical (IEC 60156)" },
      { label: "Standards", value: "IEC 60156, IS 335, ASTM D877/D1816" },
    ],
  },
  {
    slug: "transformer-turns-ratio-tester",
    name: "Transformer Turns Ratio Tester",
    category: "Transformer Diagnostics",
    categorySlug: "primary-test-equipment",
    tagline: "Automated Turns Ratio & Vector Group Verification",
    description:
      "The transformer turns ratio (TTR) test verifies that a transformer's winding ratio matches its nameplate specification and that all tap positions are correct. Green Watt's TTR tester provides fast, accurate automated ratio measurement for transformers from distribution level to EHV.",
    features: [
      "Automatic ratio measurement — calculates ratio and deviation from nominal",
      "Wide ratio range: 0.8 to 10,000+ covering distribution to EHV transformers",
      "Tests all OLTC and OCTC tap positions sequentially",
      "Phase angle measurement to verify winding polarity and vector group",
      "Vector group verification (Dyn11, YNyn0, etc.)",
      "Ratio error measurement to ±0.1% or better",
      "Automatic three-phase testing in a single connection setup",
      "Safety protection — HV detection circuit prevents incorrect connection damage",
    ],
    applications: [
      "Commissioning of new power and distribution transformers",
      "Periodic maintenance testing to detect tap changer problems and shorted turns",
      "Post-repair verification after transformer rewinding or bushing replacement",
      "Factory acceptance testing at transformer manufacturing works",
      "Post-lightning or fault event assessment",
    ],
    specs: [
      { label: "Ratio Range", value: "0.8 to 10,000 (or higher)" },
      { label: "Ratio Accuracy", value: "±0.1% or better" },
      { label: "Phase Angle Accuracy", value: "±1 minute" },
      { label: "Standards", value: "IEC 60076-1, IS 2026, IEEE C57.12.90" },
    ],
  },
  {
    slug: "winding-resistance-tester",
    name: "Winding Resistance Tester",
    category: "Transformer Diagnostics",
    categorySlug: "primary-test-equipment",
    tagline: "DC Winding Resistance Test Set for Transformers & Motors",
    description:
      "DC winding resistance measurement reveals turn-to-turn short circuits, loose or corroded tap-changer contacts, broken conductor strands, and high-resistance joints. Green Watt's winding resistance tester delivers fast, accurate measurement with automatic demagnetisation, minimising test time on large power transformer windings.",
    features: [
      "High test current: multiple ranges (1 A, 10 A, 100 A) for all winding types",
      "Wide resistance range: micro-ohms (µΩ) to kilo-ohms (kΩ) in a single instrument",
      "Simultaneous three-phase measurement greatly accelerates testing",
      "Automatic demagnetisation — protects transformer on re-energisation",
      "Tap-changer testing: continuous resistance monitoring during OLTC operation",
      "Temperature correction to 75°C or 20°C reference",
      "Colour touchscreen with real-time resistance curve display",
      "Internal memory with USB download and report generation",
    ],
    applications: [
      "Commissioning and maintenance of power and distribution transformers",
      "On-load tap changer (OLTC) dynamic resistance testing",
      "Motor and generator winding resistance measurement",
      "Reactor and inductor winding resistance verification",
      "Post-repair verification of rewound transformers",
    ],
    specs: [
      { label: "Test Current Ranges", value: "1 A, 10 A, 100 A" },
      { label: "Measurement Range", value: "µΩ to kΩ" },
      { label: "Standards", value: "IEC 60076-1, IS 2026, IEEE C57.12.90" },
      { label: "Interface", value: "Colour touchscreen, USB" },
    ],
  },
  {
    slug: "energy-meters",
    name: "Energy Meters",
    category: "Metering & Power Quality",
    categorySlug: "meters-clamps",
    tagline: "On-Site Reference Energy Meters for Field Verification",
    description:
      "Green Watt supplies on-site reference energy meters for the verification and calibration of revenue-grade and industrial energy meters in the field. These portable reference standards allow metering engineers and utility inspection teams to test installed meters without removing them from service.",
    features: [
      "Class 0.05 accuracy or better across the full range",
      "1-phase (GW-EMR1) and 3-phase (GW-EMR3) models available",
      "Direct connection or clamp-on current input options",
      "Real-time display of power, energy, power factor, and frequency",
      "Simultaneous display of all three phases (EMR3)",
      "RS-232 / USB communication for automated test reporting",
      "Rugged housing for substation and outdoor environments",
      "Complies with IS 16444 / IEC 62053 accuracy requirements",
    ],
    applications: [
      "Revenue meter verification and audit by utility inspection teams",
      "Post-installation commissioning check of LT and HT energy meters",
      "Periodic statutory verification per CEA (Meters) Regulations",
      "Energy audit and loss-reduction programmes by DISCOMs",
    ],
    specs: [
      { label: "Accuracy Class", value: "Class 0.05 or better" },
      { label: "Models", value: "GW-EMR1 (1-phase), GW-EMR3 (3-phase)" },
      { label: "Communication", value: "RS-232, USB" },
      { label: "Standards", value: "IS 16444, IEC 62053" },
    ],
  },
  {
    slug: "clamp-meters",
    name: "Clamp Meters",
    category: "Metering & Power Quality",
    categorySlug: "meters-clamps",
    tagline: "Standard & Monster Jaw Clamp Meters for Current Measurement",
    description:
      "Clamp meters allow current measurement on live conductors without breaking the circuit. Green Watt supplies a range from standard models for everyday electrical work through to heavy-duty monster-jaw clamps for large busbar and cable bundle applications commonly found in main incomer panels and transformer LV terminals.",
    features: [
      "True-RMS AC current measurement up to 600 A (standard) or 3000 A (monster jaw)",
      "Monster jaw: 85 mm+ opening for large busbars and bundled cables",
      "Inrush current capture mode for motor starting current measurement",
      "Low-pass filter mode for accurate VFD/inverter environment readings",
      "AC/DC voltage measurement up to 1000 V",
      "Resistance, continuity, diode, and capacitance measurement",
      "Bluetooth data transmission (model dependent)",
      "CAT IV 600 V safety rating",
    ],
    applications: [
      "Transformer LV terminal and feeder current measurement",
      "Motor load current verification and imbalance checking",
      "Energy audit and load survey work",
      "Solar PV string current measurement (DC clamp models)",
      "Large industrial busbar current measurement without panel shutdown",
    ],
    specs: [
      { label: "Standard Jaw Opening", value: "40 mm" },
      { label: "Monster Jaw Opening", value: "85 mm or greater" },
      { label: "Max Current (Monster Jaw)", value: "3000 A AC" },
      { label: "Voltage Range", value: "Up to 1000 V AC/DC" },
      { label: "Safety Rating", value: "CAT IV 600 V" },
    ],
  },
  {
    slug: "multimeter",
    name: "Digital Multimeter",
    category: "Metering & Power Quality",
    categorySlug: "meters-clamps",
    tagline: "Professional-Grade Digital Multimeters for Electrical Work",
    description:
      "Green Watt's professional digital multimeters are built to the demanding standards of substation and industrial electrical maintenance. With true-RMS measurement, wide measurement ranges, and robust CAT IV safety ratings, they are the everyday tools of choice for Green Watt's field engineers and our clients' maintenance teams.",
    features: [
      "True-RMS voltage and current measurement for accurate readings on non-sinusoidal waveforms",
      "Auto-ranging with manual range override",
      "AC/DC voltage up to 1000 V, AC/DC current measurement",
      "Resistance, continuity (with audible beeper), diode test",
      "Capacitance and frequency measurement",
      "Temperature measurement with thermocouple input",
      "Data hold, min/max/average recording functions",
      "Backlit display for use in dimly lit switchrooms",
      "CAT III 1000 V / CAT IV 600 V safety rating",
    ],
    applications: [
      "Substation LV DC and AC voltage and current checks",
      "Motor and generator terminal voltage measurement",
      "Cable and switchgear continuity testing",
      "Battery charger and DCDB voltage monitoring",
      "General electrical installation testing and fault finding",
    ],
    specs: [
      { label: "AC/DC Voltage", value: "Up to 1000 V" },
      { label: "Resistance", value: "Up to 100 MΩ" },
      { label: "True RMS", value: "Yes" },
      { label: "Safety Rating", value: "CAT III 1000 V / CAT IV 600 V" },
    ],
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export const productCategories = [
  {
    title: "PD, IR / UV",
    items: products.filter((p) => p.categorySlug === "pd-ir-uv"),
  },
  {
    title: "Transformer Diagnostics",
    items: products.filter((p) => p.categorySlug === "primary-test-equipment"),
  },
  {
    title: "Protection & Relay Testing",
    items: products.filter((p) => p.categorySlug === "relay-testing"),
  },
  {
    title: "Solar PV Testing",
    items: products.filter((p) => p.categorySlug === "solar-pv"),
  },
  {
    title: "HV & Insulation Testing",
    items: products.filter((p) => p.categorySlug === "hv-insulation"),
  },
  {
    title: "Metering & Clamps",
    items: products.filter((p) => p.categorySlug === "meters-clamps"),
  },
];
